services:
  postgres:
    image: postgres:15
    container_name: liferay-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: liferay
      POSTGRES_PASSWORD: password
      POSTGRES_DB: liferay_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared-network

  liferay:
    image: liferay/dxp:2025.q1.1-lts
    container_name: liferay1
    ports:
      - "8080:8080"
    environment:
      - LIFERAY_JDBC_DEFAULT_DRIVER_CLASS_NAME= org.postgresql.Driver
      - LIFERAY_JDBC_DEFAULT_URL= jdbc:postgresql://postgres:5432/liferay_db
      - LIFERAY_JDBC_DEFAULT_USERNAME= liferay
      - LIFERAY_JDBC_DEFAULT_PASSWORD= password
      - LIFERAY_VALID_HOSTS=liferay,139.59.78.220
    depends_on:
      - postgres
    volumes:
      - liferay_data:/opt/liferay/data
      - liferay_logs:/opt/liferay/logs
      - liferay_deploy:/opt/liferay/deploy
      - liferay_osgi:/opt/liferay/osgi
      - liferay_config:/opt/liferay/home
    networks:
      - shared-network
  
  springboot-api:
    build:
      context: ./springboot-rfq-cx
      dockerfile: Dockerfile
    container_name: springboot-rfq-cx
    ports:
      - "8081:8081"
    depends_on:
      - liferay
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge

volumes:
  postgres_data:
  liferay_data:
  liferay_logs:
  liferay_deploy:
  liferay_osgi:
  liferay_config:
  liferay_home:
  